# Default initial positions for ovis's ros2_control fake system

initial_positions:
  arm_joint_1: -0.3
  arm_joint_2: -0.15
  arm_joint_3: 0.2
  arm_joint_4: 1.6
  arm_joint_5: 0.3
  arm_joint_6: -0.2